### ISSUE TITLE
Error when executing the Python Test Prioritizer

### ISSUE THREAD

**Issue by lethal233** [christianbirchler-org/sdc-scissor#96]
# Steps to reproduce the bug

1. Go to https://github.com/christianbirchler-org/sdc-scissor/tree/main/sdc_scissor/sdc_prioritizer/testPrioritization
2. clone this repo
3. `cd sdc-scissor/sdc_scissor/sdc_prioritizer`
4. `. docker_scripts/build-test-prioritization-image.sh `
5. `. docker_scripts/run-test-prioritization-container.sh`

# Resulting and expected behavior
* I get an error 
```bash
Stopping and removing existing container...
15bffed469190f0257f081efd78a1fe93b5c22ae7bc557ccde96885fad08efcc
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "python3": cannot run executable found relative to current directory: unknown.
Error response from daemon: Container 15bffed469190f0257f081efd78a1fe93b5c22ae7bc557ccde96885fad08efcc is not running
```
We should step into the docker container through this command.

# Screen recording or screenshot
<img width="691" alt="image" src="https://github.com/christianbirchler-org/sdc-scissor/assets/47763046/2a132a4c-4157-4144-afd8-33336a3b374e">

# System information
* OS: Ubuntu 22.04
* CPU: X86_64 intel i7-12700KF
* GPU: NVIDIA RTX 3090Ti
* Software: latest version of SDC-Scissor

**Comment by ChristianBirchler** [comment]
@lethal233 , thanks for the issue. I also now get some issues regarding docker and the version of the base image. I will work on it. Currently, I am busy with a conference. I guess I will fix the issue within the next 2-3 weeks.

**Comment by lethal233** [comment]
> @lethal233 , thanks for the issue. I also now get some issues regarding docker and the version of the base image. I will work on it. Currently, I am busy with a conference. I guess I will fix the issue within the next 2-3 weeks.

Thanks for the help! Really appreciate it!

**Comment by ChristianBirchler** [comment]
@lethal233
On my side it works now by strictly following the [instructions](https://github.com/christianbirchler-org/sdc-scissor/tree/main/sdc_scissor/sdc_prioritizer/testPrioritization). Let me know if it also works for you.

Cheers,
Christian

**Comment by lethal233** [comment]
> @lethal233 On my side it works now by strictly following the [instructions](https://github.com/christianbirchler-org/sdc-scissor/tree/main/sdc_scissor/sdc_prioritizer/testPrioritization). Let me know if it also works for you.
> 
> Cheers, Christian

It works now! Thanks so much for your help! If I have any question, I will post it here!
